
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MINUSCULAS = 17;
  public static final int INTERROGACION = 13;
  public static final int CADENA = 22;
  public static final int CONCATENACION = 9;
  public static final int DOSPUNTOS = 3;
  public static final int CARACTERES = 20;
  public static final int SUMA = 12;
  public static final int FLECHA = 4;
  public static final int LLAVEC = 8;
  public static final int LLAVEA = 7;
  public static final int TILDE = 6;
  public static final int PORCENTAJE = 14;
  public static final int CARACTER = 21;
  public static final int COMA = 5;
  public static final int NUMEROS = 19;
  public static final int EOF = 0;
  public static final int ASTERISCO = 11;
  public static final int CONJ = 2;
  public static final int DISYUNCION = 10;
  public static final int MAYUSCULAS = 18;
  public static final int error = 1;
  public static final int IDENTIFICADOR = 16;
  public static final int PUNTO_Y_COMA = 15;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "CONJ",
  "DOSPUNTOS",
  "FLECHA",
  "COMA",
  "TILDE",
  "LLAVEA",
  "LLAVEC",
  "CONCATENACION",
  "DISYUNCION",
  "ASTERISCO",
  "SUMA",
  "INTERROGACION",
  "PORCENTAJE",
  "PUNTO_Y_COMA",
  "IDENTIFICADOR",
  "MINUSCULAS",
  "MAYUSCULAS",
  "NUMEROS",
  "CARACTERES",
  "CARACTER",
  "CADENA"
  };
}

